### ISSUE TITLE
1.3 support

### ISSUE THREAD

**Issue by THABBuzzkill** [saurfang/spark-sas7bdat#4]
Running into this..

java.lang.NoClassDefFoundError: org/apache/spark/sql/types/AtomicType
        at com.github.saurfang.sas.spark.SasRelation.inferSchema(SasRelation.scala:111)

Digging around, I see murmers that AtomicType was introduced in 1.4.  Does sas7bdat support 1.3?  The readme seems to indicate it does.

Thanks!

**Comment by saurfang** [comment]
Confirmed. Will take a look...

**Comment by saurfang** [comment]
Unfortunately I don't think this issue is fixable at least as a published artifact. If you need this for Spark 1.3, you can clone the project, change `sparkVersion := "1.3.0"`, then use `sbt assembly` to create an assembly jar. Afterwards, you can run spark-submit or spark-shell and include the jar in `--jars` argument.
